[target.armv7-unknown-linux-gnueabihf]
image = "cross/armv7:v1"

[target.armv7-unknown-linux-gnueabihf.env]
passthrough = [
    "RUSTFLAGS",
]

[target.aarch64-unknown-linux-gnu]
image = "cross/armv8:v1"

[target.aarch64-unknown-linux-gnu.env]
passthrough = [
    "RUSTFLAGS",
]